#!/usr/bin/env python3
"""Track 4.3 benchmark: decoupled vs coupled steady-state transport.

Arms (identical scalar discretization and time-step grids within each variant):

  DECOUPLED : the velocity field u_bar is computed ONCE (steady solve, cached to
              out/transport/u_cache.npz) and only the scalar transport
              dC/dt + u.grad C = D laplacian(C) is re-solved per injection with
              u(x,t) = u_bar(x) (1 + a sin(wt)).
  COUPLED   : u AND C are re-solved per injection: the steady flow problem is
              re-assembled and re-solved at the injection's total flow rate
              Q_blood + Q_inj (power injectors add 1-5 mL/s to ~15 mL/s of
              blood flow), then the same scalar transport is marched with that
              field.

Outputs: out/transport/report.json (machine) + out/transport/report.md (human),
per-variant curves under out/transport/compare/ .

Usage: python phase2/transport/compare.py --grid 48
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
import math
import os
import sys
import time

# see decoupled_transport.py: pin BLAS threads before numpy loads
os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")
os.environ.setdefault("OMP_NUM_THREADS", "1")

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import decoupled_transport as dtp  # noqa: E402

TOOL = "phase2/transport/compare.py"
VERSION = "1.0.0"

EQUATION = "dC/dt + u . grad(C) = D * laplacian(C)"

DISCRETIZATION = """\
Scalar transport (finite volume, cell centred, conservative flux form):
  advection : 2nd-order upwind face reconstruction
              u_f > 0: C_f = C_L + 1/2 (C_L - C_LL);  u_f < 0: C_f = C_R - 1/2 (C_RR - C_R)
              (1st-order upwind fallback where the 2nd upwind donor cell is not fluid)
  diffusion : 2nd-order central face gradients, zero flux across lumen walls
  time      : forward Euler with CFL-controlled substepping shared by both arms,
              dt = min( CFL / sum_d max|u_d| (1+a) / h_d , 0.5 / (2 D sum_d 1/h_d^2) )
  boundary  : inlet Dirichlet bolus C_in(t) (flow-diluted square bolus, tanh edges),
              outlet advective outflow (zero-gradient ghosts).
Velocity field (computed once per anatomy in the decoupled arm, per injection in
the coupled arm): steady Stokes -mu grad^2 u + grad p = f, div u = 0 on the
staggered MAC grid of the synthetic tubular domain (streamwise periodic,
no-slip staircase lumen walls, constant body force calibrated to the target
flow rate); saddle system reduced to its SPD Schur complement and solved with
preconditioned CG.  Cardiac periodicity is imposed analytically:
  u(x,t) = u_bar(x) (1 + a sin(omega t)),  a = 0.2, HR = 72 bpm (omega = 2 pi HR/60).
"""


def curve_error(times_a, c_a, times_b, c_b, n_grid=2048):
    """max |Cb - Ca| / max(Cb) on a shared grid (peak-normalised max deviation)."""
    tgrid = np.linspace(0.0, max(times_a[-1], times_b[-1]), n_grid)
    ca = np.interp(tgrid, times_a, np.nan_to_num(c_a))
    cb = np.interp(tgrid, times_b, np.nan_to_num(c_b))
    peak_b = float(cb.max())
    denom = max(peak_b, 1e-300)
    rel = float(np.abs(cb - ca).max() / denom)
    band = cb >= 0.25 * peak_b
    # pointwise relative error inside the peak band (where the curve carries signal)
    rel_pt = float((np.abs(cb - ca)[band] / np.maximum(cb[band], 1e-12)).max()) if band.any() else float("nan")
    return {
        "outlet_curve_rel_error_max": rel,
        "outlet_curve_rel_error_peakband": rel_pt,
        "tgrid": tgrid, "ca": ca, "cb": cb,
    }


def t_rise_half(times, c, peak):
    idx = np.nonzero(c >= 0.5 * peak)[0]
    return float(times[idx[0]]) if idx.size else float("nan")


def build_report_md(rep: dict) -> str:
    s = rep["settings"]
    rows = rep["per_variant_rows"]
    L = []
    L.append("# Track 4.3 - Decoupled vs Coupled Contrast-Transport Benchmark\n")
    L.append(f"Generated by `{rep['tool']}` v{rep['tool_version']} on {rep['created']} "
             f"(grid {s['grid']}^3, HR {s['modulation']['heart_rate_bpm']:g} bpm, "
             f"a = {s['modulation']['amp']:g}).\n")
    L.append("## Governing equation\n")
    L.append("Blood-borne contrast transport (advection-dominated at arterial velocities):\n")
    L.append(f"    {rep['equation']}\n")
    L.append("## Discretization\n")
    L.append("```\n" + rep["discretization"] + "```\n")
    L.append("## Benchmark protocol\n")
    L.append(
        "* **DECOUPLED**: steady velocity solve once (cached), scalar transport re-solved "
        "per injection (arbitrary bolus volume / rate / diffusivity).\n"
        "* **COUPLED**: steady velocity solve **and** scalar transport re-solved per "
        "injection, at the injection's total flow rate Q_blood + Q_inj (the injector's "
        "1-5 mL/s is not negligible against ~15 mL/s of blood flow).\n"
        "* Both arms share the identical scalar discretization AND the identical time-step "
        "grid within a variant (dt = min over both arms' CFL bounds) so that discretization "
        "noise cancels in the fidelity metric.\n"
        "* `t_coupled = t_velocity + t_transport`, `t_decoupled = t_transport` per injection; "
        "the one-time cache build is counted once in `t_decoupled_total_s`.\n"
        "* `outlet_curve_rel_error_max` = max_t |C_dec - C_coup| / max_t C_coup over the "
        "recorded window (peak-normalised max deviation of the outlet arrival curve).\n")
    L.append("## Headline numbers\n")
    L.append("| metric | value |")
    L.append("|---|---|")
    L.append(f"| injection variants | {rep['n_variants']} |")
    L.append(f"| t_coupled_total | {rep['t_coupled_total_s']:.1f} s |")
    L.append(f"| t_decoupled_total (incl. one-time cache build) | {rep['t_decoupled_total_s']:.1f} s |")
    L.append(f"| speedup mean | {rep['speedup_mean']:.2f}x |")
    L.append(f"| speedup max | {rep['speedup_max']:.2f}x |")
    L.append(f"| outlet curve rel. error max | {rep['outlet_curve_rel_error_max']:.4f} |")
    L.append("")
    L.append("## Per-variant results\n")
    L.append("| case | V [mL] | Q_inj [mL/s] | D [m^2/s] | t_vel [s] | t_tr_coup [s] | "
             "t_tr_dec [s] | t_coup [s] | t_dec [s] | speedup | curve err | t50 coup [s] | t50 dec [s] |")
    L.append("|---|---|---|---|---|---|---|---|---|---|---|---|---|")
    for r in rows:
        L.append(
            f"| {r['case_id']} | {r['volume_ml']:g} | {r['rate_mlps']:g} | {r['diffusivity_m2s']:.0e} "
            f"| {r['t_velocity_s']:.1f} | {r['t_transport_coupled_s']:.1f} | {r['t_transport_decoupled_s']:.1f} "
            f"| {r['t_coupled_s']:.1f} | {r['t_decoupled_s']:.1f} | {r['speedup']:.2f} "
            f"| {r['outlet_curve_rel_error_max']:.4f} | {r['t_half_coupled_s']:.3f} | {r['t_half_decoupled_s']:.3f} |")
    L.append("")
    L.append("## Speedup factor distribution\n")
    d = rep["speedup_distribution"]
    L.append(f"min {d['min']:.2f}x, p25 {d['p25']:.2f}x, median {d['median']:.2f}x, "
             f"p75 {d['p75']:.2f}x, max {d['max']:.2f}x, mean {d['mean']:.2f}x, std {d['std']:.3f}\n")
    L.append("```")
    for line in rep["speedup_histogram"]:
        L.append(line)
    L.append("```\n")
    L.append("## Arrival-curve fidelity (vs coupled reference)\n")
    L.append(f"* max relative error at the outlet: **{rep['outlet_curve_rel_error_max']:.4f}** "
             f"(worst variant `{rep['outlet_curve_rel_error_worst_case']}`)")
    L.append(f"* median {rep['outlet_curve_rel_error_median']:.4f}, "
             f"mean {rep['outlet_curve_rel_error_mean']:.4f}")
    L.append(f"* peak-band pointwise relative error max: {rep['outlet_curve_rel_error_peakband_max']:.4f}")
    L.append(f"* arrival-time (t50) shift max: {rep['arrival_shift_max_s']:.3f} s\n")
    L.append("## Validation\n")
    v = rep["validation"]
    L.append(f"* straight-tube Poiseuille check (grid {v['poiseuille']['grid']}): max rel. profile "
             f"error {v['poiseuille']['max_rel_err_core']:.2%} (core), rms {v['poiseuille']['rms_rel_err_core']:.2%} "
             "- consistent with the O(h) staircase wall discretization")
    L.append(f"* linear-solver residual (relative, 2-norm): max {v['solver_residual_max']:.2e}")
    L.append(f"* Stokes linearity re-scaling check (per-variant re-solve vs analytic rescale of the "
             f"baseline field): max rel. deviation {v['linearity_rescale_rel_err_max']:.2e}")
    L.append(f"* conservative flux form: mass-balance residual max {v['mass_balance_rel_max']:.2e} "
             "(round-off accumulation over the substep sum; conservation is exact by construction)")
    L.append(f"* achieved flow vs target: max rel. deviation {v['flow_target_rel_err_max']:.2e}\n")
    L.append("## Notes & interpretation\n")
    for note in rep["notes"]:
        L.append(f"* {note}")
    L.append("")
    L.append("## Reproduction\n")
    L.append("```sh\n" + rep["command"] + "\n```\n")
    return "\n".join(L)


def histogram(values, bins=8, width=44):
    lo, hi = min(values), max(values)
    if hi <= lo:
        hi = lo + 1e-9
    edges = np.linspace(lo, hi, bins + 1)
    counts, _ = np.histogram(values, bins=edges)
    lines = []
    for i in range(bins):
        bar = "#" * int(round(width * counts[i] / max(counts.max(), 1)))
        lines.append(f"[{edges[i]:6.2f},{edges[i+1]:6.2f}) | {bar} {counts[i]}")
    return lines


def run_benchmark(args) -> dict:
    geom = dtp.default_geometry()
    modulation = dtp.default_modulation(args.hr, args.amp)
    dom = dtp.build_domain(args.grid, geom)
    q_b = dtp.target_flow_m3s(geom)
    out_dir = args.out
    cmp_dir = os.path.join(out_dir, "compare")
    os.makedirs(cmp_dir, exist_ok=True)
    os.makedirs(out_dir, exist_ok=True)

    print(f"[compare] grid {args.grid}^3, Q_blood = {q_b*1e6:.2f} mL/s")
    print(f"[compare] baseline velocity solve (decoupled cache build) ...")
    t0 = time.perf_counter()
    sol_base = dtp.solve_steady_stokes(dom, q_b)
    t_cache = time.perf_counter() - t0
    cache_path = os.path.join(out_dir, "u_cache.npz")
    dtp.save_velocity_cache(cache_path, sol_base, dom, modulation, {"q_target_m3s": q_b})
    print(f"[compare]   {t_cache:.1f}s  Q = {sol_base['q_m3s']*1e6:.2f} mL/s  "
          f"res = {sol_base['residual']:.2e}")

    grid = dtp.injection_grid(_parse(args.volumes), _parse(args.rates), _parse(args.diffusivities))
    print(f"[compare] {len(grid)} injection variants, 2 arms each")
    rows = []
    t_dec_total = t_cache
    t_coup_total = 0.0
    linearity_errs = []
    for vol, rate, diff in grid:
        inj = dtp.make_injection(vol, rate, diff, q_b, args.window_extra, args.window_max)
        q_target = inj["q_total_mlps"] * 1e-6

        # --- COUPLED arm: re-solve u (at the injection's total flow) + C ---
        t0 = time.perf_counter()
        sol_c = dtp.solve_steady_stokes(dom, q_target, k_q=sol_base["k_q"])
        t_vel = time.perf_counter() - t0
        ts_c = dtp.TransportSolver(dom, sol_c, diff)
        ts_d = dtp.TransportSolver(dom, sol_base, diff)
        shared_dt = min(ts_c.dt_bound(modulation["amp"], args.cfl),
                        ts_d.dt_bound(modulation["amp"], args.cfl))
        t0 = time.perf_counter()
        res_c = ts_c.solve(inj, modulation, inj["window_s"], shared_dt=shared_dt)
        t_tr_c = time.perf_counter() - t0

        # --- DECOUPLED arm: cached u, re-solve C only ---
        t0 = time.perf_counter()
        res_d = ts_d.solve(inj, modulation, inj["window_s"], shared_dt=shared_dt)
        t_tr_d = time.perf_counter() - t0

        err = curve_error(res_d["times"], res_d["c_out"], res_c["times"], res_c["c_out"])
        t_coup = t_vel + t_tr_c
        t_dec = t_tr_d
        ratio = sol_c["f_body"] / sol_base["f_body"]
        lin_err = float(np.abs(sol_c["ux"] - ratio * sol_base["ux"]).max()
                        / max(np.abs(sol_c["ux"]).max(), 1e-300))
        linearity_errs.append(lin_err)

        peak_c, peak_d = res_c["outlet_peak"], res_d["outlet_peak"]
        row = {
            "case_id": inj["case_id"],
            "volume_ml": vol,
            "rate_mlps": rate,
            "diffusivity_m2s": diff,
            "bolus_s": inj["bolus_s"],
            "window_s": inj["window_s"],
            "dt_s": res_d["dt"],
            "n_steps": res_d["n_steps"],
            "t_velocity_s": t_vel,
            "t_transport_coupled_s": t_tr_c,
            "t_transport_decoupled_s": t_tr_d,
            "t_coupled_s": t_coup,
            "t_decoupled_s": t_dec,
            "speedup": t_coup / t_dec,
            "outlet_curve_rel_error_max": err["outlet_curve_rel_error_max"],
            "outlet_curve_rel_error_peakband": err["outlet_curve_rel_error_peakband"],
            "outlet_peak_coupled": peak_c,
            "outlet_peak_decoupled": peak_d,
            "t_half_coupled_s": t_rise_half(res_c["times"], res_c["c_out"], peak_c),
            "t_half_decoupled_s": t_rise_half(res_d["times"], res_d["c_out"], peak_d),
            "arrival_shift_s": abs(t_rise_half(res_c["times"], res_c["c_out"], peak_c)
                                   - t_rise_half(res_d["times"], res_d["c_out"], peak_d)),
            "q_target_mlps": inj["q_total_mlps"],
            "q_achieved_coupled_mlps": sol_c["q_m3s"] * 1e6,
            "solver_residual_coupled": sol_c["residual"],
            "mass_balance_rel_coupled": res_c["mass_balance_rel"],
            "mass_balance_rel_decoupled": res_d["mass_balance_rel"],
            "linearity_rescale_rel_err": lin_err,
        }
        rows.append(row)
        t_dec_total += t_dec
        t_coup_total += t_coup
        np.savez_compressed(
            os.path.join(cmp_dir, inj["case_id"] + ".npz"),
            times_dec=res_d["times"], c_out_dec=res_d["c_out"],
            times_coup=res_c["times"], c_out_coup=res_c["c_out"],
            c_in=inj["c_in"](res_c["times"]),
        )
        print(f"[compare]   {inj['case_id']:<22} vel {t_vel:6.1f}s  coup {t_coup:7.1f}s  "
              f"dec {t_dec:6.1f}s  speedup {row['speedup']:5.2f}x  err {row['outlet_curve_rel_error_max']:.4f}")

    speeds = np.array([r["speedup"] for r in rows])
    errs = np.array([r["outlet_curve_rel_error_max"] for r in rows])
    worst = rows[int(np.argmax(errs))]
    pois = dtp.validate_poiseuille(min(args.grid, 32))

    validation = {
        "poiseuille": pois,
        "solver_residual_max": float(max([sol_base["residual"]] + [r["solver_residual_coupled"] for r in rows])),
        "linearity_rescale_rel_err_max": float(max(linearity_errs)) if linearity_errs else float("nan"),
        "mass_balance_rel_max": float(max(max(r["mass_balance_rel_coupled"], r["mass_balance_rel_decoupled"])
                                          for r in rows)) if rows else 0.0,
        "flow_target_rel_err_max": float(max(abs(r["q_achieved_coupled_mlps"] - r["q_target_mlps"])
                                             / r["q_target_mlps"] for r in rows)) if rows else 0.0,
    }

    notes = [
        "The coupled arm re-solves the steady flow per injection because the power injector "
        f"materially changes the domain flow rate (Q_blood = {q_b*1e6:.2f} mL/s vs Q_inj = 1-5 mL/s). "
        "Under the strict one-way reading of the decoupling (velocity independent of injection), "
        "both arms run the identical transport discretization on identical time-step grids and the "
        "arrival curves agree to round-off; the reported error quantifies the frozen-velocity "
        "(frozen-flow-rate) approximation instead.",
        "Stokes linearity finding: the per-injection velocity solve collapses to an exact analytic "
        f"rescaling u(Q) = (Q/Q_blood) u_blood (verified to {validation['linearity_rescale_rel_err_max']:.1e}). "
        "A production decoupled predictor should therefore cache u_blood and apply the known flow-rate "
        "scaling, recovering coupled fidelity at decoupled cost; the strict frozen-u arm benchmarked "
        "here is the conservative case. (In nonlinear/in-vivo coupled CFD - non-Newtonian viscosity, "
        "fluid-structure coupling - the per-injection flow re-solve does not collapse this way.)",
        "The steady velocity model is linear Stokes (inertia neglected); at arterial Reynolds numbers "
        "O(10^2-10^3) in a mild stenosis this is the standard first-order prototype choice. Both arms "
        "use the same velocity model, so the benchmark comparison is unaffected.",
        "Arrival-curve windows are min(T_bolus + 1.5 s, 4.0 s): long injections (T_bolus up to 20 s) "
        "are recorded over their arrival transient + early plateau in both arms (identical truncation).",
        "t_decoupled_total_s includes the one-time cache build (steady velocity solve); per-injection "
        "decoupled cost is the transport re-solve alone.",
    ]

    rep = {
        "schema_version": 1,
        "tool": TOOL,
        "tool_version": VERSION,
        "command": " ".join(sys.argv),
        "created": _dt.datetime.now().isoformat(timespec="seconds"),
        "benchmark": "decoupled (u cached, C re-solved per injection) vs coupled (u + C re-solved per injection)",
        "equation": EQUATION,
        "discretization": DISCRETIZATION,
        "settings": {
            "grid": args.grid,
            "geometry": geom,
            "modulation": modulation,
            "advection_scheme": args.advection,
            "cfl": args.cfl,
            "window_extra_s": args.window_extra,
            "window_max_s": args.window_max,
            "q_blood_mlps": q_b * 1e6,
            "injection_grid": {
                "volumes_ml": _parse(args.volumes),
                "rates_mlps": _parse(args.rates),
                "diffusivities_m2s": _parse(args.diffusivities),
            },
            "dt_policy": "identical dt and step count for both arms of a variant "
                         "(min of both CFL bounds)",
        },
        # --- acceptance schema ---
        "n_variants": len(rows),
        "t_coupled_total_s": float(t_coup_total),
        "t_decoupled_total_s": float(t_dec_total),
        "speedup_mean": float(speeds.mean()) if len(rows) else float("nan"),
        "speedup_max": float(speeds.max()) if len(rows) else float("nan"),
        "outlet_curve_rel_error_max": float(errs.max()) if len(rows) else float("nan"),
        "per_variant_rows": rows,
        # --- supporting stats ---
        "speedup_distribution": {
            "min": float(speeds.min()) if len(rows) else float("nan"),
            "p25": float(np.percentile(speeds, 25)) if len(rows) else float("nan"),
            "median": float(np.median(speeds)) if len(rows) else float("nan"),
            "p75": float(np.percentile(speeds, 75)) if len(rows) else float("nan"),
            "max": float(speeds.max()) if len(rows) else float("nan"),
            "mean": float(speeds.mean()) if len(rows) else float("nan"),
            "std": float(speeds.std()) if len(rows) else float("nan"),
        },
        "speedup_histogram": histogram(list(speeds)) if len(rows) else [],
        "outlet_curve_rel_error_median": float(np.median(errs)) if len(rows) else float("nan"),
        "outlet_curve_rel_error_mean": float(errs.mean()) if len(rows) else float("nan"),
        "outlet_curve_rel_error_peakband_max": float(max(r["outlet_curve_rel_error_peakband"] for r in rows)) if rows else float("nan"),
        "outlet_curve_rel_error_worst_case": worst["case_id"] if rows else "",
        "arrival_shift_max_s": float(max(r["arrival_shift_s"] for r in rows)) if rows else float("nan"),
        "u_cache": os.path.relpath(cache_path),
        "validation": validation,
        "notes": notes,
    }
    json_path = os.path.join(out_dir, "report.json")
    with open(json_path, "w") as fh:
        json.dump(rep, fh, indent=2)
    md_path = os.path.join(out_dir, "report.md")
    with open(md_path, "w") as fh:
        fh.write(build_report_md(rep))
    print(f"[compare] wrote {json_path} and {md_path}")
    return rep


def _parse(s: str) -> tuple:
    return tuple(float(v) for v in s.split(","))


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Decoupled vs coupled transport benchmark (Track 4.3)")
    ap.add_argument("--grid", type=int, default=48, help="cells per axis (benchmark range 48-64)")
    ap.add_argument("--hr", type=float, default=72.0, help="heart rate [bpm] (60-80)")
    ap.add_argument("--amp", type=float, default=0.2, help="cardiac velocity modulation amplitude a")
    ap.add_argument("--volumes", default="5,10,20", help="bolus volumes [mL]")
    ap.add_argument("--rates", default="1,2.5,5", help="injection rates [mL/s]")
    ap.add_argument("--diffusivities", default="1e-9,1e-7,1e-6", help="contrast diffusivity [m^2/s]")
    ap.add_argument("--window-extra", type=float, default=1.5, help="curve window = bolus + extra [s]")
    ap.add_argument("--window-max", type=float, default=4.0, help="max curve window [s]")
    ap.add_argument("--cfl", type=float, default=0.4)
    ap.add_argument("--advection", choices=("upwind2", "central"), default="upwind2")
    ap.add_argument("--out", default="out/transport")
    args = ap.parse_args(argv)
    run_benchmark(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
