#!/usr/bin/env python
"""Track 4.1 — training for physics-informed neural operator surrogates.

Consumes the shared synthetic corpus contract 1 (``data/synthetic_corpus/``:
``samples/{id:05d}.npz`` with keys u/p/params/delta_p + ``index.json``). If the
corpus is absent, a DEV-SIZE conforming corpus (24 samples @ grid 32) is
generated by the inline fallback below into ``data/synthetic_corpus_dev/`` (so
it cannot collide with the real generator's output) and flagged as
``corpus: dev-fallback`` downstream.

Usage:
    .venv/bin/python phase2/surrogate/train.py --model gino|transolver \
        [--corpus data/synthetic_corpus] [--epochs 300] [--batch 4] [--lr 1e-3] \
        [--grid 32] [--out out/surrogate] [--seed 0]
"""

import argparse
import json
import math
import os
import random
import sys
import time

import numpy as np
import torch
from torch.utils.data import DataLoader, Dataset

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from models import MODEL_NAMES, build_model, count_params, rel_l2  # noqa: E402

SCHEMA_VERSION = 1
DEV_SEED = 20260923
DEV_N = 24
DEV_GRID = 32
DEV_PARAM_ORDER = [
    "Re", "D", "U_in", "stenosis_a", "stenosis_x0", "stenosis_w", "curv_c", "inlet_n",
]


# --------------------------------------------------------------------------
# Inline dev-fallback corpus generator (geometry: stenosis tube, analytic flow).
# Domain [0,1]^3; tube along x, centerline (yc(x), 0.5), yc(x) = 0.5 + c sin(2 pi x);
# local radius R(x) = R0 (1 - a exp(-((x - x0)/w)^2)), R0 = D/2.
# u_x = U_in (R0/R)^2 (1 - (rr/R)^2)^(n_eff - 1), n_eff = n + 10/Re;
# u_y = u_x (-dyc/dx) 0.5; u_z = 0 (zero outside lumen);
# p = dp0 (1 - x) - 0.5 U_in^2 ((R0/R)^2 - 1), dp0 = 2 n (1 + 50/Re).
# delta_p = mean_lumen p at x=0 minus mean_lumen p at x=1. Units: SI (m, m/s, Pa).
# --------------------------------------------------------------------------
def _dev_fields(params: np.ndarray, grid: int):
    re, d, u_in, a, x0, w, c, n = map(float, params)
    r0 = 0.5 * d
    ax = np.linspace(0.0, 1.0, grid, dtype=np.float64)
    x, y, z = np.meshgrid(ax, ax, ax, indexing="ij")
    yc = 0.5 + c * np.sin(2.0 * np.pi * x)
    dyc = c * 2.0 * np.pi * np.cos(2.0 * np.pi * x)
    rad = r0 * (1.0 - a * np.exp(-(((x - x0) / w) ** 2)))
    drad_ratio = r0 / np.maximum(rad, 1e-6)
    rr = np.sqrt((y - yc) ** 2 + (z - 0.5) ** 2)
    lumen = rr < rad
    n_eff = n + 10.0 / re
    prof = np.clip(1.0 - (rr / np.maximum(rad, 1e-6)) ** 2, 0.0, 1.0) ** max(n_eff - 1.0, 0.05)
    u_x = u_in * drad_ratio**2 * prof
    u_x = np.where(lumen, u_x, 0.0)
    u_y = np.where(lumen, u_x * (-dyc) * 0.5, 0.0)
    u = np.stack([u_x, u_y, np.zeros_like(u_x)], axis=-1).astype(np.float32)
    dp0 = 2.0 * n * (1.0 + 50.0 / re)
    p = dp0 * (1.0 - x) - 0.5 * u_in**2 * (drad_ratio**2 - 1.0)
    p = p.astype(np.float32)
    delta_p = float(p[0][lumen[0]].mean() - p[-1][lumen[-1]].mean())
    return u, p, np.float32(delta_p), lumen


def dev_generate(out_dir: str) -> str:
    """Write the DEV-SIZE conforming corpus; returns the corpus dir."""
    rng = np.random.default_rng(DEV_SEED)
    sample_dir = os.path.join(out_dir, "samples")
    os.makedirs(sample_dir, exist_ok=True)
    ranges = {
        "Re": (50.0, 300.0), "D": (0.36, 0.5), "U_in": (0.5, 1.5),
        "stenosis_a": (0.0, 0.45), "stenosis_x0": (0.3, 0.7), "stenosis_w": (0.05, 0.15),
        "curv_c": (0.0, 0.1), "inlet_n": (1.5, 2.5),
    }
    n_train = 20
    entries = []
    for i in range(DEV_N):
        params = np.array(
            [rng.uniform(*ranges[k]) for k in DEV_PARAM_ORDER], dtype=np.float32
        )
        u, p, delta_p, _ = _dev_fields(params, DEV_GRID)
        np.savez_compressed(
            os.path.join(sample_dir, f"{i:05d}.npz"),
            u=u, p=p, params=params, delta_p=delta_p,
        )
        entries.append({"id": f"{i:05d}", "split": "train" if i < n_train else "val",
                        "delta_p": float(delta_p)})
    index = {
        "schema_version": SCHEMA_VERSION,
        "generator": "flowscope phase2/surrogate/train.py dev-fallback",
        "seed": DEV_SEED,
        "grid": [DEV_GRID, DEV_GRID, DEV_GRID],
        "n_train": n_train,
        "n_val": DEV_N - n_train,
        "fields": {"u": [DEV_GRID, DEV_GRID, DEV_GRID, 3], "p": [DEV_GRID, DEV_GRID, DEV_GRID]},
        "params": {
            "order": DEV_PARAM_ORDER,
            "ranges": {k: list(v) for k, v in ranges.items()},
            "Re": {"index": 0}, "D": {"index": 1},
            "inlet_bc": {"type": "power_law_profile", "U_in_index": 2, "exponent_index": 7},
            "geometry": {
                "family": "stenosis_tube",
                "axis": "x", "centerline": "0.5 + curv_c*sin(2*pi*x)",
                "radius": "0.5*D*(1 - stenosis_a*exp(-((x-stenosis_x0)/stenosis_w)^2))",
            },
        },
        "delta_p": "Pa (inlet-plane lumen mean minus outlet-plane lumen mean)",
        "units": "SI (m, m/s, Pa)",
        "samples": entries,
    }
    with open(os.path.join(out_dir, "index.json"), "w") as f:
        json.dump(index, f, indent=1)
    return out_dir


# --------------------------------------------------------------------------
# Corpus loading (defensive against the real generator's index.json layout).
# --------------------------------------------------------------------------
def resolve_corpus(corpus: str):
    """Return (corpus_dir, index, dev_fallback: bool)."""
    if os.path.isfile(os.path.join(corpus, "index.json")):
        with open(os.path.join(corpus, "index.json")) as f:
            return corpus, json.load(f), False
    dev_dir = os.path.join(os.path.dirname(corpus.rstrip("/")), "synthetic_corpus_dev")
    dev_generate(dev_dir)
    with open(os.path.join(dev_dir, "index.json")) as f:
        index = json.load(f)
    return dev_dir, index, True


def _norm_id(v) -> str:
    if isinstance(v, str) and not v.isdigit():
        return v
    return f"{int(v):05d}"


def resolve_split(index: dict, corpus_dir: str = ""):
    """Return (train_ids, val_ids) of normalized sample ids."""
    def norm(seq):
        return [_norm_id(v if not isinstance(v, dict) else v.get("id")) for v in seq]

    split = index.get("split")
    if isinstance(split, dict) and "train" in split and "val" in split:
        return norm(split["train"]), norm(split["val"])
    if "train_ids" in index and "val_ids" in index:
        return norm(index["train_ids"]), norm(index["val_ids"])
    samples = index.get("samples")
    if isinstance(samples, dict):
        tr = [k for k, v in samples.items() if (v or {}).get("split") == "train"]
        va = [k for k, v in samples.items() if (v or {}).get("split") == "val"]
        if tr and va:
            return norm(tr), norm(va)
    if isinstance(samples, list) and samples and isinstance(samples[0], dict) and "split" in samples[0]:
        tr = [s["id"] for s in samples if s.get("split") == "train"]
        va = [s["id"] for s in samples if s.get("split") in ("val", "test", "heldout", "held_out")]
        if tr and va:
            return norm(tr), norm(va)
    ids = (
        norm(samples) if isinstance(samples, list) and samples and isinstance(samples[0], (int, str))
        else norm(index.get("ids", []))
    )
    if not ids:  # last resort: enumerate samples/ dir
        ids = sorted(
            os.path.splitext(n)[0] for n in os.listdir(os.path.join(corpus_dir, "samples"))
            if n.endswith(".npz")
        )
    ids = sorted(ids)
    n_train = int(index.get("n_train", max(1, int(0.8 * len(ids)))))
    return ids[:n_train], ids[n_train:]


def build_occupancy(params: np.ndarray, grid: int, geom_spec: dict, npz=None) -> np.ndarray:
    """Occupancy grid [1,G,G,G] (channel-first) from npz extra keys or analytic params.

    Falls back to a ones grid (whole domain fluid) when geometry is not
    reconstructable; the caller records that in metrics.
    """
    if npz is not None:
        for key in ("occ", "occupancy"):
            if key in npz:
                return npz[key].astype(np.float32)[None]
        if "sdf" in npz:
            return (npz["sdf"] < 0).astype(np.float32)[None]
    geom_spec = geom_spec or {}
    family = str(geom_spec.get("family") or geom_spec.get("type") or "").lower()
    if family in ("stenosis_tube", "stenosis-tube", "tube_stenosis"):
        _, _, _, lumen = _dev_fields(params, grid)
        return lumen.astype(np.float32)[None]
    return np.ones((1, grid, grid, grid), dtype=np.float32)


class CorpusDataset(Dataset):
    def __init__(self, corpus_dir, index, ids, grid, cond_stats=None, stride=1):
        self.corpus_dir = corpus_dir
        self.index = index
        self.ids = list(ids)
        self.grid = grid
        self.stride = stride
        self.geom_spec = ((index.get("params") or {}).get("geometry")) or {}
        first = self._load(self.ids[0])
        self.cond_dim = int(len(first["params"]))
        self.corpus_grid = first["u"].shape[0] * self.stride
        if cond_stats is None:  # fit on this split (train only)
            ps = np.stack([self._load(i)["params"] for i in self.ids])
            cond_stats = (ps.mean(axis=0), ps.std(axis=0) + 1e-6)
        self.cond_mean, self.cond_std = (np.asarray(m, dtype=np.float32) for m in cond_stats)
        family = str(self.geom_spec.get("family") or self.geom_spec.get("type") or "").lower()
        self.occ_available = (
            first["occ_npz"] is not None or first["sdf"] is not None
            or family in ("stenosis_tube", "stenosis-tube", "tube_stenosis")
        )

    def _path(self, sid):
        return os.path.join(self.corpus_dir, "samples", f"{sid}.npz")

    def _load(self, sid):
        with np.load(self._path(sid)) as d:
            s = self.stride
            occ_npz = None
            for key in ("occ", "occupancy"):
                if key in d:
                    occ_npz = d[key][::s, ::s, ::s]
                    break
            return {"u": d["u"][::s, ::s, ::s].astype(np.float32),
                    "p": d["p"][::s, ::s, ::s].astype(np.float32),
                    "params": d["params"].astype(np.float32),
                    "delta_p": np.float32(d["delta_p"]),
                    "occ_npz": occ_npz,
                    "sdf": d["sdf"][::s, ::s, ::s] if "sdf" in d else None}

    def __len__(self):
        return len(self.ids)

    def __getitem__(self, i):
        rec = self._load(self.ids[i])
        g = self.grid
        if rec["occ_npz"] is not None:
            occ = rec["occ_npz"].astype(np.float32)[None]
        elif rec["sdf"] is not None:
            occ = (rec["sdf"] < 0).astype(np.float32)[None]
        else:
            occ = build_occupancy(rec["params"], g, self.geom_spec, npz=None)
        return {
            "u": torch.from_numpy(rec["u"].copy()),
            "p": torch.from_numpy(rec["p"].copy()),
            "params": torch.from_numpy(
                (rec["params"] - self.cond_mean) / self.cond_std
            ),
            "occ": torch.from_numpy(occ),
            "delta_p": torch.tensor(float(rec["delta_p"])),
        }


def field_rms(loader: DataLoader):
    su = sp = 0.0
    nu = np_ = 0
    for b in loader:
        su += float(torch.sum(b["u"] ** 2)); nu += b["u"].numel()
        sp += float(torch.sum(b["p"] ** 2)); np_ += b["p"].numel()
    return math.sqrt(su / max(nu, 1)), math.sqrt(sp / max(np_, 1))


def run_epoch(model, loader, opt, u_rms, p_rms, train: bool, loss_kind: str = "rel_l2"):
    model.train(train)
    tot = 0.0
    nb = 0
    for b in loader:
        pred = model(b["occ"], b["params"])
        u_t = b["u"] / u_rms
        p_t = b["p"][..., None] / p_rms
        if loss_kind == "mse":
            loss = ((pred["u"] - u_t) ** 2).mean() + ((pred["p"][..., None] - p_t) ** 2).mean()
        else:
            loss = rel_l2(pred["u"], u_t).mean() + rel_l2(pred["p"][..., None], p_t).mean()
        if train:
            opt.zero_grad(set_to_none=True)
            loss.backward()
            opt.step()
        if not math.isfinite(loss.detach().item()):
            raise RuntimeError(f"non-finite loss encountered: {float(loss)}")
        tot += loss.detach().item()
        nb += 1
    return tot / max(nb, 1)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--model", required=True, choices=MODEL_NAMES)
    ap.add_argument("--corpus", default="data/synthetic_corpus")
    ap.add_argument("--out", default="out/surrogate")
    ap.add_argument("--epochs", type=int, default=300)
    ap.add_argument("--batch", type=int, default=4)
    ap.add_argument("--lr", type=float, default=1e-3)
    ap.add_argument("--loss", choices=("rel_l2", "mse"), default="rel_l2")
    ap.add_argument("--grid", type=int, default=DEV_GRID)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--train-limit", type=int, default=0,
                    help="cap train split size (CPU budget); 0 = full split")
    ap.add_argument("--val-limit", type=int, default=0,
                    help="cap val split size; 0 = full split")
    ap.add_argument("--threads", type=int, default=2,
                    help="torch intra-op threads (host is shared; 2 is fastest here)")
    args = ap.parse_args()

    if args.threads:
        torch.set_num_threads(args.threads)
    print(f"[train] torch threads={torch.get_num_threads()}")
    torch.manual_seed(args.seed)
    random.seed(args.seed)
    np.random.seed(args.seed)

    corpus_dir, index, dev_fallback = resolve_corpus(args.corpus)
    grid_spec = index.get("grid")
    corpus_grid = int(grid_spec[0] if isinstance(grid_spec, list) else (grid_spec or args.grid))
    grid = args.grid or corpus_grid
    if corpus_grid % grid:
        raise SystemExit(f"--grid {grid} must divide corpus grid {corpus_grid}")
    stride = corpus_grid // grid
    if stride > 1:
        print(f"[train] note: subsampling corpus grid {corpus_grid} -> {grid} (stride {stride})")
    train_ids, val_ids = resolve_split(index, corpus_dir)
    if args.train_limit:
        train_ids = train_ids[: args.train_limit]
    if args.val_limit:
        val_ids = val_ids[: args.val_limit]
    print(f"[train] corpus={corpus_dir} dev_fallback={dev_fallback} grid={grid} "
          f"train={len(train_ids)} val={len(val_ids)}")

    ds_train = CorpusDataset(corpus_dir, index, train_ids, grid, stride=stride)
    ds_val = CorpusDataset(corpus_dir, index, val_ids, grid,
                           cond_stats=(ds_train.cond_mean, ds_train.cond_std), stride=stride)
    dl_train = DataLoader(ds_train, batch_size=args.batch, shuffle=True)
    dl_val = DataLoader(ds_val, batch_size=args.batch)

    u_rms, p_rms = field_rms(dl_train)
    u_rms, p_rms = max(u_rms, 1e-6), max(p_rms, 1e-6)

    model = build_model(args.model, grid, ds_train.cond_dim)
    n_params = count_params(model)
    print(f"[train] model={args.model} params={n_params:,}")
    opt = torch.optim.Adam(model.parameters(), lr=args.lr)
    sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=args.epochs)

    ckpt_dir = os.path.join(args.out, "checkpoints")
    os.makedirs(ckpt_dir, exist_ok=True)
    log = {"model": args.model, "epochs": [], "command": " ".join(sys.argv),
           "torch": torch.__version__, "train_ids": train_ids, "val_ids": val_ids}
    best_val = float("inf")
    t_start = time.perf_counter()
    for ep in range(1, args.epochs + 1):
        t0 = time.perf_counter()
        tr = run_epoch(model, dl_train, opt, u_rms, p_rms, train=True, loss_kind=args.loss)
        va = run_epoch(model, dl_val, opt, u_rms, p_rms, train=False, loss_kind=args.loss)
        sched.step()
        log["epochs"].append({"epoch": ep, "train_loss": tr, "val_loss": va,
                              "lr": sched.get_last_lr()[0], "sec": time.perf_counter() - t0})
        if ep == 1 or ep % 10 == 0 or ep == args.epochs:
            print(f"[train] epoch {ep:4d}/{args.epochs} train={tr:.4f} val={va:.4f} "
                  f"({log['epochs'][-1]['sec']:.1f}s)")
        with open(os.path.join(args.out, f"train_log_{args.model}.json"), "w") as f:
            json.dump(log, f, indent=1)
        if va < best_val:
            best_val = va
            torch.save({
                "model": args.model, "state_dict": model.state_dict(), "grid": grid,
                "cond_dim": ds_train.cond_dim, "params": n_params, "epochs": ep,
                "train_loss": tr, "val_loss": va, "u_rms": u_rms, "p_rms": p_rms,
                "corpus": corpus_dir, "corpus_kind": "dev-fallback" if dev_fallback else "shared",
                "loss": args.loss,
                "train_ids": train_ids, "val_ids": val_ids,
                "cond_mean": ds_train.cond_mean.tolist(), "cond_std": ds_train.cond_std.tolist(),
                "corpus_grid": corpus_grid, "grid_stride": stride,
                "train_limit": args.train_limit or None, "val_limit": args.val_limit or None,
                "command": " ".join(sys.argv), "torch": torch.__version__,
            }, os.path.join(ckpt_dir, f"{args.model}.pt"))
    train_s = time.perf_counter() - t_start
    log["best_val_loss"] = best_val
    log["train_wall_s"] = train_s
    with open(os.path.join(args.out, f"train_log_{args.model}.json"), "w") as f:
        json.dump(log, f, indent=1)
    print(f"[train] done best_val={best_val:.4f} wall={train_s:.0f}s "
          f"-> {ckpt_dir}/{args.model}.pt")


if __name__ == "__main__":
    main()
